import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">MedwiseKursDetay</Link>
        </li>
        <li>
          <Link to="/anasayfa">Anasayfa</Link>
        </li>
        <li>
          <Link to="/magaza">Magaza</Link>
        </li>
        <li>
          <Link to="/medwisekurs">MedwiseKurs</Link>
        </li>
        <li>
          <Link to="/medwisekursfiyatlandirma">MedwiseKursFiyatlandirma</Link>
        </li>
        <li>
          <Link to="/medwiseegitimcikayit">MedwiseEgitimciKayit</Link>
        </li>
        <li>
          <Link to="/ogretmenler">Ogretmenler</Link>
        </li>
        <li>
          <Link to="/ogretmendetay">Ogretmendetay</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
